/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as pfp from "./pfp";
export type { pfp };
export type { BaseERC20 } from "./BaseERC20";
export type { BaseERC721 } from "./BaseERC721";
