/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BaseERC721__factory } from "./BaseERC721__factory";
export { MyToken__factory } from "./MyToken__factory";
